export const COLORS_FETCH_START = `COLORS_FETCH_START`;
export const COLORS_FETCH_SUCCESS = `COLORS_FETCH_SUCCESS`;
export const COLORS_FETCH_ERROR = `COLORS_FETCH_ERROR`;

export const COLORS_UPDATE_START = `COLORS_UPDATE_START`;
export const COLORS_UPDATE_SUCCESS = `COLORS_UPDATE_SUCCESS`;
export const COLORS_UPDATE_ERROR = `COLORS_UPDATE_ERROR`;
